#!/bin/bash

TMPDIR='./tmp-bands'
PSEUDO_DIR='../../Pseudopotentials'
BIN_DIR=''
#
cat > gasb.scf.in  << EOF
&control
    title = 'GaSb bulk'
    calculation = 'scf'
    verbosity='high',
    prefix='gasb_bulk_NoC',
    pseudo_dir = '$PSEUDO_DIR',
    outdir='$TMPDIR'
    etot_conv_thr=1.0e-4,
    forc_conv_thr=1.0e-3,
    disk_io='high',
    wf_collect=.true.
 /
&system    
      noncolin = .true.,
      lspinorb = .true.,
      ibrav=2, 
      celldm(1)=11.388,
      nat=2, 
      ntyp=2,
      ecutwfc =18.0, 
 /
&electrons
    mixing_beta = 0.6 
    conv_thr =  1.0d-8,
 /
ATOMIC_SPECIES
 Ga   69.72   Garel.TMSOFTER.UPF
 Sb  121.75   Sbrel.TMSOFTER.UPF
ATOMIC_POSITIONS
Ga      0.00 0.00 0.00
Sb      0.25 0.25 0.25                                                          
K_POINTS {automatic}
4 4 4 1 1 1
EOF
#
$BIN_DIR/pw.x < gasb.scf.in > gasb.scf.out 
cat > gasb.bands.in  << EOF
 &control
    title = 'GaSb bulk'
    calculation = 'bands'
    verbosity='high',
    prefix='gasb_bulk_NoC',
    pseudo_dir = '$PSEUDO_DIR',
    outdir='$TMPDIR'
    etot_conv_thr=1.0e-4,
    forc_conv_thr=1.0e-3,
    disk_io='high',
    wf_collect=.true.
 /
&system 
      noncolin = .true.,
      lspinorb = .true.,
      ibrav=2, 
      celldm(1)=11.388,
      nat=2, 
      ntyp=2,
      ecutwfc =18.0, 
      nbnd = 20,
 /
 &electrons
   diago_thr_init=5.0e-6,
   diago_full_acc=.true.
   electron_maxstep = 100,
   diagonalization='david'
   mixing_mode = 'plain'
   mixing_beta = 0.6
   conv_thr =  1.0d-8,
 /
ATOMIC_SPECIES
 Ga   69.72   Garel.TMSOFTER.UPF
 Sb  121.75   Sbrel.TMSOFTER.UPF
ATOMIC_POSITIONS
Ga      0.00 0.00 0.00
Sb      0.25 0.25 0.25
K_POINTS {tpiba_b}
3
   0.5 0.5 0.5 20 
   0.0 0.0 0.0 20 
   1.0 0.0 0.0 20 
EOF
#
$BIN_DIR/pw.x <gasb.bands.in > gasb.bands.out 
cat > gasb.bandspp.in << EOF
&bands
    prefix = "gasb_bulk_NoC",
    outdir='$TMPDIR'
    filband='gasb_bulk_NoC.dat'
    lsym=.true.
 /
EOF
$BIN_DIR/bands.x <  gasb.bandspp.in > gasb.bandspp.out
cat > gasb.plotband.in << EOF
gasb_bulk_NoC.dat
-5.0 10.0
gasb_bulk_NoC_bands.xmgr
gasb_bulk_NoC_bands.ps
1.0
5 0.0
EOF
$BIN_DIR/plotband.x < gasb.plotband.in > gasb.plotband.out
